

---

grafana_version: "latest"
grafana_port: 3000
grafana_admin_password: "admin"
grafana_root_url: "http://localhost:3000"

loki_root_url: "http://loki:3100/loki/api/v1/push"

prometheus_version: "latest"
prometheus_port: 9090

alertmanager_url: "http://alertmanager:9093"

gf_path_provisioning: "/etc/grafana/provisioning"